sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/nightly-master
    - sudo apt-get update
    - sudo apt-get -y install fish
script:
    - curl https://raw.githubusercontent.com/jorgebucaran/fisher/master/fisher.fish --create-dirs -so ~/.config/fish/functions/fisher.fish
    - fish -c "fisher version"
