sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/nightly-master
    - sudo apt-get update
    - sudo apt-get -y install fish
script:
    - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
    - fish -c "fisher version"
