sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/nightly-master
    - sudo apt-get update
    - sudo apt-get -y install fish
script:
    - curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
    - fish -c "fisher version && fisher help"
